{% set version = '1.30.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-randtoolbox
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/randtoolbox_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/randtoolbox/randtoolbox_{{ version }}.tar.gz
  sha256: 0debf6e270f4e349d6b3d9ddfd6388552495f33f4cd19c9016abfe27d5083790

build:
  merge_build_host: True  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_fortran') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}sed               # [win]
    - {{posix}}grep              # [win]
    - {{posix}}autoconf
    - {{posix}}automake          # [not win]
    - {{posix}}automake-wrapper  # [win]
    - {{posix}}pkg-config
    - {{posix}}make
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rngwell >=0.10_1
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rngwell >=0.10_1

test:
  commands:
    - $R -e "library('randtoolbox')"           # [not win]
    - "\"%R%\" -e \"library('randtoolbox')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=randtoolbox
  license: BSD_3_clause
  summary: Provides (1) pseudo random generators - general linear congruential generators,  multiple
    recursive generators and generalized feedback shift register (SF-Mersenne Twister
    algorithm and WELL generators); (2) quasi random generators - the Torus algorithm,
    the Sobol sequence, the Halton sequence (including the Van der Corput sequence)
    and (3) some generator tests - the gap test, the serial test, the poker test. See
    e.g. Gentle (2003) <doi:10.1007/b97336>. The package can be provided without the
    rngWELL dependency on demand. Take a look at the Distribution task view of types
    and tests of random number generators. Version in Memoriam of Diethelm and Barbara
    Wuertz.
  license_family: BSD

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: randtoolbox
# Type: Package
# Title: Toolbox for Pseudo and Quasi Random Number Generation and Random Generator Tests
# Version: 1.30.0
# Author: R port by Yohan Chalabi, Christophe Dutang, Petr Savicky and Diethelm Wuertz with some underlying C codes of (i) the SFMT algorithm from M. Matsumoto and M. Saito, (ii) the Knuth-TAOCP RNG from D. Knuth.
# Maintainer: Christophe Dutang <christophe.dutang@ensimag.fr>
# Description: Provides (1) pseudo random generators - general linear congruential generators,  multiple recursive generators and generalized feedback shift register (SF-Mersenne Twister algorithm and WELL generators); (2) quasi random generators - the Torus algorithm, the Sobol sequence, the Halton sequence (including the Van der Corput sequence) and (3) some generator tests - the gap test, the serial test, the poker test. See e.g. Gentle (2003) <doi:10.1007/b97336>. The package can be provided without the rngWELL dependency on demand. Take a look at the Distribution task view of types and tests of random number generators. Version in Memoriam of Diethelm and Barbara Wuertz.
# Depends: rngWELL (>= 0.10-1)
# License: BSD_3_clause + file LICENSE
# NeedsCompilation: yes
# Packaged: 2019-04-19 20:30:35 UTC; dutang
# Repository: CRAN
# Date/Publication: 2019-04-21 15:20:03 UTC
