appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: PIMAUM2htVl4XTs8v29MtePjyUriRCtYxu5yfQ30mQMzCQwUl+LvNN6ItuwSRnB2ou8Od3tIkFXLBcdI52sevpCNIDqQi3x0/NdMTHFXWliBc4nge/NQYt2/d4T2D709e6o9CbyZqQDBTRyNAyVu4hHHn/OLUtc5cuDLjIBjSemrGDRJSR9qIcmKgG+kE8XdT24Pl5gMq2aObxQpv/kMxryFURzPF70UjBORZ9FBeU0m5ZKrZi7rF8J/+OgGzBxh/RCUlBLnLLx7c7UXt7IaR7EXByRFumY8ai8LCCSvNkk/nQ3RtvQ6H8sc/QSOPUIIfWP+oVEZgpAzyd5YzJVgc30+BpeKBs4ub2QyzO3h7QbCROLRxW985tKlWtEnb3VtCF9n0b6en9VoRpbJjQwRsbMSILbORdSj57B2pPo60MDNElCNdeKvj+MLPO02Jb22cEXU0sJarnXzafLmCb5H8VJjdlIdYiVRBhtXY96xTTYcs5PbuPYnC9YoIQXuMg78ubaC7FnJatqHo3jaO7C/VpuPH7L0zCZSZAIALAwg3L/phEdXcnl04K0MCXu6sikWaqQwdnYmMeOGHuzMdwOBfj4hW/YGaXeAijkEPt/rvn9B1R6+lYq9ZAmJfQNnQyNdkk38H8L+j4/ius1mOIyLwjghkZCrT1y5Ye4X65pDsRs=}
bot:
  automerge: true
